# Generated by Django 5.1.7 on 2025-04-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_mymodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyModel",
        ),
    ]
